# Generated by Django 3.0.8 on 2020-08-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0002_auto_20200725_1743'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=10)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('authority', models.CharField(blank=True, max_length=10)),
                ('ref_id', models.CharField(blank=True, max_length=10)),
                ('food_trans', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='food.FoodTransaction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paytrans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ['لیست تراکنش'],
                'verbose_name_plural': ['لیست تراکنش ها'],
                'ordering': ['-date_created'],
            },
        ),
    ]
