# Generated by Django 3.0.8 on 2020-08-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200725_1743'),
        ('zarinpal', '0002_auto_20200804_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='food.SiteWallet'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='food_trans',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='food.FoodTransaction'),
        ),
    ]
