# Generated by Django 3.0.8 on 2020-07-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thefood',
            name='image',
            field=models.ImageField(blank=True, height_field=250, null=True, upload_to='', width_field=250),
        ),
    ]
