# Generated by Django 3.0.8 on 2020-07-19 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200717_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kind', models.TextField(choices=[('DP', 'واریز'), ('WD', 'برداشت')])),
            ],
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone_number',
            field=models.IntegerField(error_messages={'unique': 'این شماره قبلا ثبت شده است'}, help_text='شماره در 10 رقم به صورت  ******9', null=True, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.CreateModel(
            name='SiteWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='مقدار حساب')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
