# Generated by Django 3.0.6 on 2020-07-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200723_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thefood',
            name='food_transaction',
        ),
        migrations.AddField(
            model_name='foodtransaction',
            name='foods',
            field=models.ManyToManyField(to='food.TheFood'),
        ),
    ]
